# Use root/example as user/password credentials
version: '3.1'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
#    image: docker-gs-ping
    ports:
      - 9000:9000
#    networks:
#      - mynet
#    links:
#      - db
#    depends_on:
#      - database

#  db:
#    #    restart: always
#    image: mariadb
#    container_name: myapp_db
#    environment:
#      - MYSQL_USER=db_user
#      - MYSQL_PASSWORD=db_user_pass
#      - MYSQL_DATABASE=app_db
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - 3306:3306
#    volumes:
#      - ./mysql-dump:/docker-entrypoint-initdb.d
##    volumes:
##      - dbdata:/var/lib/mysql

  db:
    image: postgres
    container_name: myapp_db
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_user_pass
      - POSTGRES_DB=app_db

volumes:
  mysql-dump:

#volumes:
#  dbdata:
# docker exec -it id_cont bash